<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>sts2_recolor</AssemblyName>
    <RootNamespace>SpireRecolor</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GameDir>H:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64</GameDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2"><HintPath>$(GameDir)\sts2.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="GodotSharp"><HintPath>$(GameDir)\GodotSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameDir)\0Harmony.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>

</Project>
